### ISSUE TITLE
Allow for Javascript event handlers for incoming patches

### ISSUE THREAD

**Issue by Starcounter-Jack** [PuppetJs/PuppetJs#1]
If the developer does *not* want to use data binding, he/she should perhaps be able to add event handlers in the browser when the server sends patches. This enables the use of traditional imperative code using legacy stuff, JQuery or other frameworks.

The main parameters are the path to the view-model element/property and the call back function with an event parameter hosting the new data.

Pseudo code concept:

```js
puppet.call_me_when_server_sends_stuff( "page.company.name", function(changed) { 
    console.log("The server changed the name of the company");
});
```

WDYT?

**Comment by miyconst** [comment]
This has been implemented in scope of issue:
https://github.com/Polyjuice/starcounter-debug-aid/issues/20

Because of:
1. The `onRemoteChange` callback of PuppetJs has only one (*Object* `data`) parameter and for the issue above *String* `url` also required. 
2. There is no callback for outcoming changes.
3. The callback name `onLocalChange` would be misleading, there may be a request to the server without any local change - user clicks a link.

Two new callbacks were created:
1. `onPatchReceived` (*String* `data`, *String* `url`).
2. `onPatchSent` (*String* `data`, *String* `url`).

Unlike `onRemoteChange` the new callbacks pass raw string data instead of evaluated object. Both of the callbacks serve HTTP and WebSocket requests. The `url` parameter may be used to determine request type.

The `onRemoteChange` callback is now deprecated and should be removed soon.

&lt;puppet-client&gt; now has `patchreceived` & `patchsent` events, read more at the project's page:
https://github.com/PuppetJs/puppet-client/tree/starcounter-debug-aid

**Comment by warpech** [comment]
Closing as solved.
