### ISSUE TITLE
Change the way PuppetJS obtains the initial JSON

### ISSUE THREAD

**Issue by warpech** [PuppetJs/PuppetJs#58]
As mentioned in https://github.com/Starcounter/InvoiceDemo/issues/14, IE11 throws `Network Error 0x2ef3` when trying to make POST or PATCH xhr request, unless there was a GET request before to the same URL.

This would be solved if we changed the way in which we obtain the initial JSON.

Currently we are doing: 

```http
GET /
X-Referer: /__default/483D3E341CAC89F710000030
Accept: application/json
```

What we could be doing:

```http
GET /__default/483D3E341CAC89F710000030
Accept: application/json
```

This returns the same JSON and moreover:

- fixes IE11
- does not call `/` application handler twice on page load

@tomalec, @chrhol, @Starcounter-Jack ?

**Comment by tomalec** [comment]
:+1:

##### Implementation detail:
The only question I have is to the way to build URL from given remote URL:

 1. `puppet.remoteUrl + reffererCookie` quick easy, bug prone
 2. `new URL(reffererCookie, puppet.remoteURL)` less performant than string concat, another point that requires [Polymer/URL](https://github.com/Polymer/URL), which we require anyway, and it's native in Chrome and shimmed with WebComponentes polyfill, however we thought about skipping that with separating WebSocket URL calculation outside of core PuppetJs engine. However, is more booletproof, and adaptive as then Session creation URL could be any valid URL.

**Comment by warpech** [comment]
@chrol, @Starcounter-Jack - what's your opinion?

**Comment by warpech** [comment]
@chrhol, @Starcounter-Jack - what's your opinion?

**Comment by warpech** [comment]
After giving it a second thought, I think it is pretty straightforward:

Puppet server sets the location at which it wants to be asked about current resource with any of the following headers:

1. `Location: XXXX`
2. `X-Location: XXXX`
3. `Set-Cookie:Location=XXXX; path=/`

Cases 2. and 3. only exist because JavaScript cannot read case 1. in a web browser.

Practically it means that we should rename `this.referer` to `this.remoteUrl `. When server sends a value for any of the above mentioned headers, the value replaces `this.remoteURL`.

@miyconst could you apply this change? We should peer-review it and test it before releasing a new version.

**Comment by miyconst** [comment]
The property `this.remoteURL` is readonly, should I make it writeable?

**Comment by warpech** [comment]
Yes

**Comment by tomalec** [comment]
Do we really want to change the original remoteurl given by user? so the url which will be the base for WebSocket request, or just compose the URL for HTTP Patch communication?

**Comment by warpech** [comment]
What would be the reason to keep the original `remoteUrl`? Server, by providing `Location / X-Location / Cookie: Location`, tells that it expects to be requested about the resource using the new URL, so the original URL becomes is useless in my opinion. Am I missing something?

About the WebSocket, we could consider creating a new `webSocketUpgradeUrl` property in a separate issue, as currently it is hardcoded on line https://github.com/PuppetJs/PuppetJs/blob/gh-pages/src/puppet.js#L215 (`this.referer.replace(/(\/?)__([^\/]*)\//g, "/__$2/wsupgrade/")`). Do you agree?

**Comment by tomalec** [comment]
But currently `webSocketUpgradeUrl` is build out of `puppet.wsURL` which is build out of `remoteURL` should it then be build on updated on original one?

If we would build/fetch `webSocketUpgradeUrl` in other way, I agree that we should make `remoteURL` writable.

**Comment by tomalec** [comment]
So maybe we could go with 
 1. `initURL` is given in constructor, 
 2. then server may return `httpURL` and `wsURL` 
With such case server may force specific channel (only one URL returned), or give a free hand to client (send both).

Pros:
 1. Extremely clean client code,

Cons:
 1. Changes to server-side needed

**Comment by Starcounter-Jack** [comment]
Let's do a hangout at 13:00 today. We should review the spec. Keep the below principles in mind when reasoning about this:

## Core usage 

At the core, the server side JSON document (puppet) must be able to be created using REST principles. This is important as some client implementation would prefer this as it makes puppets easy to implement. This scenario means that the client should issue a POST to ask for the creating of a new resource on the server. The server should then respond with a standard location header. To repeat the clean usage:

1. Client asks for html using GET /homepage with accept:text/html header
2. Server responds with html
3. Client asks for new puppet json using POST /puppets with accept:application/json header
4. Server responds with json and the location header
5. Client can optionally send PATCH requests...

## Optimized usage

To avoid the latency of the dual roundtrip above, we need to provide optimizations. This must be done without breaking the clean usage. What we do is to precreate the server side json document in the hope that the client will not ask for it to be created explicitly. We also provide optional ws support.

So let us examine the optimations.

### Precreation

The server cheats by precreating the JSON resource on the initial http GET with Accept:html and returns it in x-Location (thus the client does not need to send POST). The server does not break the unoptimized flow because if the client can essentially ignore this header and send the POST request. In this case the server will respond with a standard location header.

### Websockets

We provide a websocket upgrade. This process should follow common practise. Our websocket option essentially supports the PATCH traffic that usually follows after the initial browser http html GET without any http overhead and with full duplex communication (server push)

**Comment by Starcounter-Jack** [comment]
Forget my last post. I see the problem with it. Still, lets do a hangout

**Comment by Starcounter-Jack** [comment]
Unforget the post. I think it might work as a principle if we update the spec.

**Comment by warpech** [comment]
We can't meet at 13:00 because there is company lunch at that time. I will announce some other time.

@Starcounter-Jack proposes to make a more formal spec of the Puppet protocol (#61)

I don't think it imposes any change to our current incremental improvements approach, so let's continue with doing the fix in topic. Current issue could be fixed with one line of code. We can discuss it at today's meeting at 10.

**Comment by miyconst** [comment]
Changes after today's discussion with @warpech and @tomalec:

1. `this.remoteURL` is now writeable.
2. `this.remoteURL` is set to `new URL(this.referer, this.remoteUrl).href` in `PuppetNetworkChannel.prototype.setReferer`.

@tomalec take a look please.

**Comment by tomalec** [comment]
Suite of WebSocket tests fails as `this.remoteUrl = new URL(this.referer, this.remoteUrl).href;` throws an error if `this.remoteURL` is not defined.

**Comment by miyconst** [comment]
After discussion with @tomalec we agreed on:

1. Establish connection with original `remoteUrl`.
2. Execute `handleResponseCookie` after connection established, but not on the first page load.
3. Update `remoteUrl`, so the patches will be send to the location received from #1.
4. Remove `this.referer`, leave `this.remoteUrl` only.

**Comment by miyconst** [comment]
Finally done. There is no more `referer` in `puppet.js`.

1. All usage of `remoteUrl` was replaced with `referer`.
2. `referer` was renamed to `remoteUrl`.

All tests from puppetjs solution pass.

**Comment by warpech** [comment]
@tomalec can you review?
