### ISSUE TITLE
Change the way to build/obtain Web Socket upgrade URL

### ISSUE THREAD

**Issue by tomalec** [PuppetJs/PuppetJs#60]
Currently `webSocketUpgradeUrl` is build out of `puppet.wsURL` which is build out of `remoteURL`. And all that happens after initial HTTP request, using `this.referer`.

It is way to complicated and lead to other issues #58, #59 

It would be nice to:
 1. Untangle `referer`, `remoteURL` dependencies, (will make solving #58 way much easier)
 2. Do not hardcode a thing, (currently we do `.replace(/(\/?)__([^\/]*)\//g, "/__$2/wsupgrade/")`)
 3. Make it possible to open WS without HTTP - #59

**Comment by warpech** [comment]
Good ideas, but let's not do any development before we first describe points 2 and 3 on wiki.

**Comment by warpech** [comment]
Update:

1. This is already solved
2. Please fix and release this the same day as https://github.com/Starcounter/Starcounter/issues/2791
3. This is already solved. In future it can be extended to obtaining the whole viewmodel through WS (without `application/json` request on bootstrap), because why not! It is just an idea... There is no issue about that
