### ISSUE TITLE
What if perform full page redirect instead of showing session lost error?

### ISSUE THREAD

**Issue by miyconst** [PuppetJs/PuppetJs#63]
Currently if I press a morphed link after server restart (i.e. start/stop an app) an exception on console appears: `Session lost. Server replied with a different session ID that was already set.`.

What if make full page redirect instead of showing that error?

**Comment by warpech** [comment]
I agree that this is a problem that needs to be solved. The proposed solution might be desired in production mode, but it masks the problem instead of solving it. And I am not sure if it is actually a problem.

## A. It masks the problem instead of solving it

What you proposed is simply:

1. Client asks: give me `/people/person/5`
2. Server says: here is what you wanted, session id: `AAAA`
3. Client asks: please change the `FirstName$` of this person
4. Server says: here is *something*, session id: `BBBB`
5. Client asks:  give me `/people/person/5`
6. Server says: here is what you wanted, session id: `CCCC` 

Response at point 4 is only potentially a problem, because we don't know if this *something* is something we can trust to be a valid response. Did the server reset the session (which is probably an **error**) or does it only renew the session ID (which is probably **fine**)?

Currently, in this case, client shows an ugly error message `Session lost.`

## B. I am not sure if it is actually a problem

As said above, renewing session ID is probably fine, as long as the server performs what it was asked to do. So instead of showing the error, the client should just apply the patch and replace `this.remoteUrl` with the new session id.

I think the real problem comes from the fact that server replaces the root object and that is something which should show an error or at least a warning. 

@tomalec WDYT?

**Comment by tomalec** [comment]
What about:

- A.4.a. (server renewed same session, and identified both view-models)
Server says: here is what you wanted, change `FullName`, new session id: `BBBB`
- A.5.a. Client applies patch, and updates `this.remoteUrl`


- A.4.b. (server restarts the session, as something went wrong)
Server says: here you have full JSON viewm-model, and new session id: `BBBB`
- A.5.b. Client may show an error. 

@warpech but what should we do with "change the `FirstName$`" Patch in reset case?

**Comment by warpech** [comment]
The remaining question is how to identify the error case (b):

1. It is an error if a party replaces the root object
2. It is an error if a party sends a version number (`_ver#s`) lower or equal than the previously sent version number. So that after sending `_ver#s: 5` it is considered an error to send `_ver#s: 0`

Solution 1 is somehow limiting but makes sense to me... Session is like serving food in one bowl. You can serve the food, replace the food, rename the bowl, wash the bowl to put new stuff there - but this is the same instance of the bowl (in our words: the same session root). Once you replace the bowl, the state is broken and this is an error.

Solution 2 relies on OT being enabled, which can be an additional check, but we cannot rely only on it.

**Comment by tomalec** [comment]
:stew: I like the food story :)

Ad. 2. JSON Patch Queue already throws an error - https://github.com/PuppetJs/JSON-Patch-Queue/blob/gh-pages/src/json-patch-queue.js#L61

**Comment by warpech** [comment]
I propose the following solution:

1. If server replies with a patch that replaces the root (any patch where `op` is add/replace/delete and `path` is an empty string), PuppetJs calls `console.error` with `Puppet error. The server replaced the session` and then **applies** the patch.
2. The above situation should be overridable with a custom `<template>` which displays a friendly error message on the screen. Inside this template we may even put a `<puppet-redirect url="current">` to achieve the solution proposed by @miyconst in his first message.
2. If server replies with a new session ID (`remoteUrl`), it is fine. PuppetJs should take it and replace the previous `remoteUrl`

WDYT?

**Comment by tomalec** [comment]
I like the idea, but I'm not sure how would you override PuppetJS Js behaviour with HTML template

**Comment by warpech** [comment]
PuppetJs allows to provide a callback and PuppetDom uses that callback?

**Comment by tomalec** [comment]
but Puppet-dom is still a pure JS script  not a custom element, and have nothing to do with template

**Comment by warpech** [comment]
PuppetDom is DOM-aware, as the name says... So it can support stamping out templates that are provided via options or as a child element of `<puppet-client>`.

**Comment by warpech** [comment]
Related: https://github.com/Starcounter/Starcounter/issues/3084

**Comment by miyconst** [comment]
Right now Session is maintained with empty patches every 15 seconds. Closing this issue as outdated.
