### ISSUE TITLE
Session reconnection in case of lost response

### ISSUE THREAD

**Issue by warpech** [PuppetJs/PuppetJs#71]
As discussed in https://github.com/PuppetJs/PuppetJs/issues/37#issuecomment-112757820 downwards, there may be a time where server response (e.g. `_ver#s: 2`) is irreversably lost due to network error. 

This is a case when the server created a message `_ver#s: 2`, but it never reached the client. In result, the following server responses `_ver#s: 3`, `_ver#s: 4` will queue up on the client forever, while the client still is waiting for `_ver#s: 2`.

The solution should enable a nice Gmail-style reconnection message, as explained here: http://ux.stackexchange.com/questions/83371/web-app-is-offline-show-reconnecting-in-countdown

![](http://i.stack.imgur.com/pWgVX.png)

@tomalec could you wrap up the proposed solution?

This is a long term stability improvement, no need to do it immediately.

**Comment by warpech** [comment]
Related: https://github.com/Starcounter/Starcounter/issues/3084

**Comment by tomalec** [comment]
Proposition for 

## Session re-establish flow

1. Local changes are made:
 1. PuppetJS sends messages
 2. `puppet.queue` adds versions, etc
 3. `puppet.queue` typeof `-OT-agent` keeps a list of  `.pending/.pendingVersionedPatches` with all Versioned-JSON-Patches
as well as (at least for internal use) `.pendingMessages/.pendingPatches`

2. Somebody decides to re-establish connection, due to WS timeout, connection lost, whatever
  ### A - local decision
 4. Puppet re-establishes connection, with some flags, that this is "re-established", not new connection, and with most recent state (versions) of queue
 5. Puppet sends once again all `.queue.pending` changes

 ### B remote decision 
 4. Remote (for example Starcounter Puppeteer) reestablished connection with its local, remote, ack versions
 5. Remote sends all its pending patches
 6. Puppet calls `.queue.receive( allRemotesPendingPatches, silent = true)`
so queue will silently disregards already applied patches

**Comment by warpech** [comment]
Good idea! What we are still missing is to describe the protocol for "re-establishing" the connection. The primary work needs to be done in the [spec](https://github.com/PuppetJs/PuppetJs/wiki/Server-communication:-advanced-synchronization), then agreed with @chrhol and finally implemented.

There is no chance of finishing it this year, so let's get back to it in January.

**Comment by dan31** [comment]
This is the main issue to track session reconnection issue. CC @malx122.
To finish the work, @warpech assgined @joozek78.

**Comment by malx122** [comment]
Any news on this?

**Comment by joozek78** [comment]
I implemented session resumption and retransmission for a scenario client frames are lost, but I need to tidy the code up and implement the other direction of retransmission

**Comment by warpech** [comment]
@tomalec could you review this today? 
@joozek78 does reviewing it require a custom build of Starcounter? can you provide the installer?

**Comment by warpech** [comment]
Pull requests:

- https://github.com/PuppetJs/PuppetJs/pull/90
- https://github.com/PuppetJs/puppet-polymer-client/pull/28

**Comment by joozek78** [comment]
I'll post the installer

**Comment by warpech** [comment]
@joozek78 is https://github.com/Starcounter/Starcounter/pull/3747 ready for review as well?

**Comment by joozek78** [comment]
Finally, I was able to release version [2.1.0](https://github.com/PuppetJs/PuppetJs/releases/tag/2.1.0) of puppetjs, which introduces reconnection. Please see [readme](https://github.com/PuppetJs/PuppetJs/releases/tag/2.1.0)  for details. This version should be included in next version of Starcounter
