### ISSUE TITLE
Honor url hash

### ISSUE THREAD

**Issue by mattiasmak** [PuppetJs/PuppetJs#84]
I have a question/request that would help us a lot. I can describe the use case in detail if needed. But in short: when morphing url, can you honor the hash part of the url? I understand that you don't use the url hash and do not intend to so it won't have an impact for you in any negative way.

**Comment by warpech** [comment]
How would you like the hash part to be honored? Can you write an example scenario?

**Comment by mattiasmak** [comment]
Leave it as it is basically. Now any hash is overwritten

**Comment by warpech** [comment]
Some questions:

1. do you mean morphing pages via clicking on links (`<a>`) or redirection (`<puppet-redirect>`)
2. do you really intent the URL to contain state? it is because it should be bookmarkable, etc?

**Comment by warpech** [comment]
Closing as won't fix, because this is against web standards. In HTML, clicking on a `<a>` element does not preserve the previous hash value. PuppetJs should not change that.

I understand that you have a particular problem with it, but I think it needs to be solved inside if your application (for example by LocalStorage, or by custom event handlers set on your `<a>` elements).

@mattiasmak please reopen if you'd like to further discuss. Since we did not implement it, I wonder what turned out to be your final solution.
