### ISSUE TITLE
Puppetjs has way to many heartbeats, and heartbeats trigger to much on the server

### ISSUE THREAD

**Issue by malx122** [PuppetJs/PuppetJs#92]
Every 5 seconds puppetjs is triggering a heartbeat that make the server go throw all properties...
Are heartbeat really necessary at all?

**Comment by malx122** [comment]
What I mean is that there is no reason to detect that the network is down when the user does nothing. It should be enough that it detects and reconnect when user tries do do something or with a much longer interval.

**Comment by joozek78** [comment]
You always need the server (or rather that we can't assume you don't need it) - remember that server can send you patches on its own. Imagine a messenger app, where you check connection only when you "use" the server (i.e. send some patches). If your connection was broken you'd want to know about it (because it would prevent you from receiving a message), but you wouldn't - until you typed something. You would probably have a population of users idly typing just to be sure their connection is working :)

You can always configure heartbeats interval with `ping-interval-s` attribute on `puppet-client` element.
As for triggering too much, that's a mistake and we're in process of fixing this (see #94). This should be included in upcoming release
