### ISSUE TITLE
PuppetJs cancels xhr request to a new page if it takes too long time to load

### ISSUE THREAD

**Issue by miyconst** [PuppetJs/PuppetJs#93]
This lineof PuppetJs: https://github.com/PuppetJs/PuppetJs/blob/gh-pages/src/puppet.js#L433 cancels pending requests which take too long time to proceed.

cc @warpech, @joozek78

**Comment by warpech** [comment]
I detected the same problem yesterday: https://github.com/StarcounterPrefabs/SignIn/issues/40#issuecomment-243470601

@joozek78 can you explain if this is necessary? It is very developer unfriendly.

**Comment by miyconst** [comment]
Initially it was made to avoid two active reconnection requests. If the first one takes too long Puppet sends another one and when both succeed we have two active WS connections.

**Comment by warpech** [comment]
Assigning to @joozek78. He is fixing this.

**Comment by joozek78** [comment]
It turns out that even if long requests alone don't trigger the reconnection, setting a breakpoint will freeze all threads and prevent heartbeat from getting a response. Thus, we decided to set the default heartbeat interval to 60s - that way we're developer-friendly and developers can tune it themselves to provide better experience to their users

**Comment by joozek78** [comment]
Fix has now been pushed to starcounter develop.
